/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { CardContent, Card } from "@/components/ui/card"

export function DropDown({title, account}) {
  return (
    (<div className="mb-3">
      <Card className="shadow-lg bg-white">
        <CardContent className="p-6">
          <h2 className="text-2xl font-semibold">{title}</h2>
          <Accordion className="w-full mt-4" collapsible="" type="multiple">
          {account?.youtube_data?.email_newsletter.content_analysis.map((item, index)=>(
            <AccordionItem key={index} value={`item-${index+1}`}>
              <AccordionTrigger className="hover:underline-none">
                {item.topic}
              </AccordionTrigger>
              <AccordionContent>{item.content}</AccordionContent>
            </AccordionItem>
          ))}
          </Accordion>
        </CardContent>
      </Card>
    </div>)
  );
}
